export default {
  login: 'wrongakram',
  id: 31742755,
  node_id: 'MDQ6VXNlcjMxNzQyNzU1',
  avatar_url: 'https://avatars1.githubusercontent.com/u/31742755?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/wrongakram',
  html_url: 'https://github.com/wrongakram',
  followers_url: 'https://api.github.com/users/wrongakram/followers',
  following_url:
    'https://api.github.com/users/wrongakram/following{/other_user}',
  gists_url: 'https://api.github.com/users/wrongakram/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/wrongakram/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/wrongakram/subscriptions',
  organizations_url: 'https://api.github.com/users/wrongakram/orgs',
  repos_url: 'https://api.github.com/users/wrongakram/repos',
  events_url: 'https://api.github.com/users/wrongakram/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/wrongakram/received_events',
  type: 'User',
  site_admin: false,
  name: 'Akram Khalid',
  company: null,
  blog: 'https://www.youtube.com/c/wrongakram',
  location: null,
  email: null,
  hireable: null,
  bio: 'Front End Developer and UI/UX Designer',
  twitter_username: null,
  public_repos: 39,
  public_gists: 0,
  followers: 572,
  following: 0,
  created_at: '2017-09-07T18:12:55Z',
  updated_at: '2020-12-15T19:57:46Z',
}
