export default [
  {
    login: 'joshua-isaac',
    id: 40035381,
    node_id: 'MDQ6VXNlcjQwMDM1Mzgx',
    avatar_url: 'https://avatars2.githubusercontent.com/u/40035381?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/joshua-isaac',
    html_url: 'https://github.com/joshua-isaac',
    followers_url: 'https://api.github.com/users/joshua-isaac/followers',
    following_url:
      'https://api.github.com/users/joshua-isaac/following{/other_user}',
    gists_url: 'https://api.github.com/users/joshua-isaac/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/joshua-isaac/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/joshua-isaac/subscriptions',
    organizations_url: 'https://api.github.com/users/joshua-isaac/orgs',
    repos_url: 'https://api.github.com/users/joshua-isaac/repos',
    events_url: 'https://api.github.com/users/joshua-isaac/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/joshua-isaac/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'flex2016',
    id: 26524099,
    node_id: 'MDQ6VXNlcjI2NTI0MDk5',
    avatar_url: 'https://avatars1.githubusercontent.com/u/26524099?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/flex2016',
    html_url: 'https://github.com/flex2016',
    followers_url: 'https://api.github.com/users/flex2016/followers',
    following_url:
      'https://api.github.com/users/flex2016/following{/other_user}',
    gists_url: 'https://api.github.com/users/flex2016/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/flex2016/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/flex2016/subscriptions',
    organizations_url: 'https://api.github.com/users/flex2016/orgs',
    repos_url: 'https://api.github.com/users/flex2016/repos',
    events_url: 'https://api.github.com/users/flex2016/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/flex2016/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'vishvaRam',
    id: 44122284,
    node_id: 'MDQ6VXNlcjQ0MTIyMjg0',
    avatar_url: 'https://avatars0.githubusercontent.com/u/44122284?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/vishvaRam',
    html_url: 'https://github.com/vishvaRam',
    followers_url: 'https://api.github.com/users/vishvaRam/followers',
    following_url:
      'https://api.github.com/users/vishvaRam/following{/other_user}',
    gists_url: 'https://api.github.com/users/vishvaRam/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/vishvaRam/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/vishvaRam/subscriptions',
    organizations_url: 'https://api.github.com/users/vishvaRam/orgs',
    repos_url: 'https://api.github.com/users/vishvaRam/repos',
    events_url: 'https://api.github.com/users/vishvaRam/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/vishvaRam/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'djlone',
    id: 11168251,
    node_id: 'MDQ6VXNlcjExMTY4MjUx',
    avatar_url: 'https://avatars0.githubusercontent.com/u/11168251?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/djlone',
    html_url: 'https://github.com/djlone',
    followers_url: 'https://api.github.com/users/djlone/followers',
    following_url: 'https://api.github.com/users/djlone/following{/other_user}',
    gists_url: 'https://api.github.com/users/djlone/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/djlone/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/djlone/subscriptions',
    organizations_url: 'https://api.github.com/users/djlone/orgs',
    repos_url: 'https://api.github.com/users/djlone/repos',
    events_url: 'https://api.github.com/users/djlone/events{/privacy}',
    received_events_url: 'https://api.github.com/users/djlone/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'HBenzaoui',
    id: 8946252,
    node_id: 'MDQ6VXNlcjg5NDYyNTI=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/8946252?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HBenzaoui',
    html_url: 'https://github.com/HBenzaoui',
    followers_url: 'https://api.github.com/users/HBenzaoui/followers',
    following_url:
      'https://api.github.com/users/HBenzaoui/following{/other_user}',
    gists_url: 'https://api.github.com/users/HBenzaoui/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/HBenzaoui/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/HBenzaoui/subscriptions',
    organizations_url: 'https://api.github.com/users/HBenzaoui/orgs',
    repos_url: 'https://api.github.com/users/HBenzaoui/repos',
    events_url: 'https://api.github.com/users/HBenzaoui/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/HBenzaoui/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Runo-saduwa',
    id: 35904727,
    node_id: 'MDQ6VXNlcjM1OTA0NzI3',
    avatar_url: 'https://avatars3.githubusercontent.com/u/35904727?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Runo-saduwa',
    html_url: 'https://github.com/Runo-saduwa',
    followers_url: 'https://api.github.com/users/Runo-saduwa/followers',
    following_url:
      'https://api.github.com/users/Runo-saduwa/following{/other_user}',
    gists_url: 'https://api.github.com/users/Runo-saduwa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Runo-saduwa/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Runo-saduwa/subscriptions',
    organizations_url: 'https://api.github.com/users/Runo-saduwa/orgs',
    repos_url: 'https://api.github.com/users/Runo-saduwa/repos',
    events_url: 'https://api.github.com/users/Runo-saduwa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Runo-saduwa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'm-abdelwahab',
    id: 27310414,
    node_id: 'MDQ6VXNlcjI3MzEwNDE0',
    avatar_url: 'https://avatars2.githubusercontent.com/u/27310414?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/m-abdelwahab',
    html_url: 'https://github.com/m-abdelwahab',
    followers_url: 'https://api.github.com/users/m-abdelwahab/followers',
    following_url:
      'https://api.github.com/users/m-abdelwahab/following{/other_user}',
    gists_url: 'https://api.github.com/users/m-abdelwahab/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/m-abdelwahab/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/m-abdelwahab/subscriptions',
    organizations_url: 'https://api.github.com/users/m-abdelwahab/orgs',
    repos_url: 'https://api.github.com/users/m-abdelwahab/repos',
    events_url: 'https://api.github.com/users/m-abdelwahab/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/m-abdelwahab/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'esamqoul',
    id: 11042427,
    node_id: 'MDQ6VXNlcjExMDQyNDI3',
    avatar_url: 'https://avatars2.githubusercontent.com/u/11042427?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/esamqoul',
    html_url: 'https://github.com/esamqoul',
    followers_url: 'https://api.github.com/users/esamqoul/followers',
    following_url:
      'https://api.github.com/users/esamqoul/following{/other_user}',
    gists_url: 'https://api.github.com/users/esamqoul/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/esamqoul/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/esamqoul/subscriptions',
    organizations_url: 'https://api.github.com/users/esamqoul/orgs',
    repos_url: 'https://api.github.com/users/esamqoul/repos',
    events_url: 'https://api.github.com/users/esamqoul/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/esamqoul/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mayowDev',
    id: 43674732,
    node_id: 'MDQ6VXNlcjQzNjc0NzMy',
    avatar_url: 'https://avatars2.githubusercontent.com/u/43674732?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mayowDev',
    html_url: 'https://github.com/mayowDev',
    followers_url: 'https://api.github.com/users/mayowDev/followers',
    following_url:
      'https://api.github.com/users/mayowDev/following{/other_user}',
    gists_url: 'https://api.github.com/users/mayowDev/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mayowDev/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mayowDev/subscriptions',
    organizations_url: 'https://api.github.com/users/mayowDev/orgs',
    repos_url: 'https://api.github.com/users/mayowDev/repos',
    events_url: 'https://api.github.com/users/mayowDev/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mayowDev/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'LasCC',
    id: 43119034,
    node_id: 'MDQ6VXNlcjQzMTE5MDM0',
    avatar_url: 'https://avatars2.githubusercontent.com/u/43119034?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/LasCC',
    html_url: 'https://github.com/LasCC',
    followers_url: 'https://api.github.com/users/LasCC/followers',
    following_url: 'https://api.github.com/users/LasCC/following{/other_user}',
    gists_url: 'https://api.github.com/users/LasCC/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/LasCC/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/LasCC/subscriptions',
    organizations_url: 'https://api.github.com/users/LasCC/orgs',
    repos_url: 'https://api.github.com/users/LasCC/repos',
    events_url: 'https://api.github.com/users/LasCC/events{/privacy}',
    received_events_url: 'https://api.github.com/users/LasCC/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'GramosI7',
    id: 35958572,
    node_id: 'MDQ6VXNlcjM1OTU4NTcy',
    avatar_url: 'https://avatars1.githubusercontent.com/u/35958572?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/GramosI7',
    html_url: 'https://github.com/GramosI7',
    followers_url: 'https://api.github.com/users/GramosI7/followers',
    following_url:
      'https://api.github.com/users/GramosI7/following{/other_user}',
    gists_url: 'https://api.github.com/users/GramosI7/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/GramosI7/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/GramosI7/subscriptions',
    organizations_url: 'https://api.github.com/users/GramosI7/orgs',
    repos_url: 'https://api.github.com/users/GramosI7/repos',
    events_url: 'https://api.github.com/users/GramosI7/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/GramosI7/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'daisykumar',
    id: 56020145,
    node_id: 'MDQ6VXNlcjU2MDIwMTQ1',
    avatar_url: 'https://avatars3.githubusercontent.com/u/56020145?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daisykumar',
    html_url: 'https://github.com/daisykumar',
    followers_url: 'https://api.github.com/users/daisykumar/followers',
    following_url:
      'https://api.github.com/users/daisykumar/following{/other_user}',
    gists_url: 'https://api.github.com/users/daisykumar/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/daisykumar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daisykumar/subscriptions',
    organizations_url: 'https://api.github.com/users/daisykumar/orgs',
    repos_url: 'https://api.github.com/users/daisykumar/repos',
    events_url: 'https://api.github.com/users/daisykumar/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daisykumar/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'radityaputranto',
    id: 18069998,
    node_id: 'MDQ6VXNlcjE4MDY5OTk4',
    avatar_url: 'https://avatars1.githubusercontent.com/u/18069998?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/radityaputranto',
    html_url: 'https://github.com/radityaputranto',
    followers_url: 'https://api.github.com/users/radityaputranto/followers',
    following_url:
      'https://api.github.com/users/radityaputranto/following{/other_user}',
    gists_url: 'https://api.github.com/users/radityaputranto/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/radityaputranto/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/radityaputranto/subscriptions',
    organizations_url: 'https://api.github.com/users/radityaputranto/orgs',
    repos_url: 'https://api.github.com/users/radityaputranto/repos',
    events_url: 'https://api.github.com/users/radityaputranto/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/radityaputranto/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jaeyholic',
    id: 32690370,
    node_id: 'MDQ6VXNlcjMyNjkwMzcw',
    avatar_url: 'https://avatars0.githubusercontent.com/u/32690370?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jaeyholic',
    html_url: 'https://github.com/jaeyholic',
    followers_url: 'https://api.github.com/users/jaeyholic/followers',
    following_url:
      'https://api.github.com/users/jaeyholic/following{/other_user}',
    gists_url: 'https://api.github.com/users/jaeyholic/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jaeyholic/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jaeyholic/subscriptions',
    organizations_url: 'https://api.github.com/users/jaeyholic/orgs',
    repos_url: 'https://api.github.com/users/jaeyholic/repos',
    events_url: 'https://api.github.com/users/jaeyholic/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jaeyholic/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mehmetvarol',
    id: 22845520,
    node_id: 'MDQ6VXNlcjIyODQ1NTIw',
    avatar_url: 'https://avatars2.githubusercontent.com/u/22845520?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mehmetvarol',
    html_url: 'https://github.com/mehmetvarol',
    followers_url: 'https://api.github.com/users/mehmetvarol/followers',
    following_url:
      'https://api.github.com/users/mehmetvarol/following{/other_user}',
    gists_url: 'https://api.github.com/users/mehmetvarol/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mehmetvarol/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mehmetvarol/subscriptions',
    organizations_url: 'https://api.github.com/users/mehmetvarol/orgs',
    repos_url: 'https://api.github.com/users/mehmetvarol/repos',
    events_url: 'https://api.github.com/users/mehmetvarol/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mehmetvarol/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'masterharsh',
    id: 22725968,
    node_id: 'MDQ6VXNlcjIyNzI1OTY4',
    avatar_url: 'https://avatars2.githubusercontent.com/u/22725968?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/masterharsh',
    html_url: 'https://github.com/masterharsh',
    followers_url: 'https://api.github.com/users/masterharsh/followers',
    following_url:
      'https://api.github.com/users/masterharsh/following{/other_user}',
    gists_url: 'https://api.github.com/users/masterharsh/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/masterharsh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/masterharsh/subscriptions',
    organizations_url: 'https://api.github.com/users/masterharsh/orgs',
    repos_url: 'https://api.github.com/users/masterharsh/repos',
    events_url: 'https://api.github.com/users/masterharsh/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/masterharsh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ScottFred',
    id: 1937793,
    node_id: 'MDQ6VXNlcjE5Mzc3OTM=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/1937793?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ScottFred',
    html_url: 'https://github.com/ScottFred',
    followers_url: 'https://api.github.com/users/ScottFred/followers',
    following_url:
      'https://api.github.com/users/ScottFred/following{/other_user}',
    gists_url: 'https://api.github.com/users/ScottFred/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ScottFred/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ScottFred/subscriptions',
    organizations_url: 'https://api.github.com/users/ScottFred/orgs',
    repos_url: 'https://api.github.com/users/ScottFred/repos',
    events_url: 'https://api.github.com/users/ScottFred/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ScottFred/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'gregcorby',
    id: 2355013,
    node_id: 'MDQ6VXNlcjIzNTUwMTM=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/2355013?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gregcorby',
    html_url: 'https://github.com/gregcorby',
    followers_url: 'https://api.github.com/users/gregcorby/followers',
    following_url:
      'https://api.github.com/users/gregcorby/following{/other_user}',
    gists_url: 'https://api.github.com/users/gregcorby/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/gregcorby/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gregcorby/subscriptions',
    organizations_url: 'https://api.github.com/users/gregcorby/orgs',
    repos_url: 'https://api.github.com/users/gregcorby/repos',
    events_url: 'https://api.github.com/users/gregcorby/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/gregcorby/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'hendry3k',
    id: 51496873,
    node_id: 'MDQ6VXNlcjUxNDk2ODcz',
    avatar_url: 'https://avatars1.githubusercontent.com/u/51496873?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hendry3k',
    html_url: 'https://github.com/hendry3k',
    followers_url: 'https://api.github.com/users/hendry3k/followers',
    following_url:
      'https://api.github.com/users/hendry3k/following{/other_user}',
    gists_url: 'https://api.github.com/users/hendry3k/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hendry3k/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hendry3k/subscriptions',
    organizations_url: 'https://api.github.com/users/hendry3k/orgs',
    repos_url: 'https://api.github.com/users/hendry3k/repos',
    events_url: 'https://api.github.com/users/hendry3k/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hendry3k/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'chimexi42',
    id: 51214351,
    node_id: 'MDQ6VXNlcjUxMjE0MzUx',
    avatar_url: 'https://avatars2.githubusercontent.com/u/51214351?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/chimexi42',
    html_url: 'https://github.com/chimexi42',
    followers_url: 'https://api.github.com/users/chimexi42/followers',
    following_url:
      'https://api.github.com/users/chimexi42/following{/other_user}',
    gists_url: 'https://api.github.com/users/chimexi42/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/chimexi42/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/chimexi42/subscriptions',
    organizations_url: 'https://api.github.com/users/chimexi42/orgs',
    repos_url: 'https://api.github.com/users/chimexi42/repos',
    events_url: 'https://api.github.com/users/chimexi42/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/chimexi42/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'and000',
    id: 1727613,
    node_id: 'MDQ6VXNlcjE3Mjc2MTM=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/1727613?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/and000',
    html_url: 'https://github.com/and000',
    followers_url: 'https://api.github.com/users/and000/followers',
    following_url: 'https://api.github.com/users/and000/following{/other_user}',
    gists_url: 'https://api.github.com/users/and000/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/and000/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/and000/subscriptions',
    organizations_url: 'https://api.github.com/users/and000/orgs',
    repos_url: 'https://api.github.com/users/and000/repos',
    events_url: 'https://api.github.com/users/and000/events{/privacy}',
    received_events_url: 'https://api.github.com/users/and000/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'PragunSaini',
    id: 41020076,
    node_id: 'MDQ6VXNlcjQxMDIwMDc2',
    avatar_url: 'https://avatars1.githubusercontent.com/u/41020076?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/PragunSaini',
    html_url: 'https://github.com/PragunSaini',
    followers_url: 'https://api.github.com/users/PragunSaini/followers',
    following_url:
      'https://api.github.com/users/PragunSaini/following{/other_user}',
    gists_url: 'https://api.github.com/users/PragunSaini/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/PragunSaini/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/PragunSaini/subscriptions',
    organizations_url: 'https://api.github.com/users/PragunSaini/orgs',
    repos_url: 'https://api.github.com/users/PragunSaini/repos',
    events_url: 'https://api.github.com/users/PragunSaini/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/PragunSaini/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'vale-c',
    id: 21361479,
    node_id: 'MDQ6VXNlcjIxMzYxNDc5',
    avatar_url: 'https://avatars2.githubusercontent.com/u/21361479?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/vale-c',
    html_url: 'https://github.com/vale-c',
    followers_url: 'https://api.github.com/users/vale-c/followers',
    following_url: 'https://api.github.com/users/vale-c/following{/other_user}',
    gists_url: 'https://api.github.com/users/vale-c/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/vale-c/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/vale-c/subscriptions',
    organizations_url: 'https://api.github.com/users/vale-c/orgs',
    repos_url: 'https://api.github.com/users/vale-c/repos',
    events_url: 'https://api.github.com/users/vale-c/events{/privacy}',
    received_events_url: 'https://api.github.com/users/vale-c/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Bayo19',
    id: 47965593,
    node_id: 'MDQ6VXNlcjQ3OTY1NTkz',
    avatar_url: 'https://avatars3.githubusercontent.com/u/47965593?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Bayo19',
    html_url: 'https://github.com/Bayo19',
    followers_url: 'https://api.github.com/users/Bayo19/followers',
    following_url: 'https://api.github.com/users/Bayo19/following{/other_user}',
    gists_url: 'https://api.github.com/users/Bayo19/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Bayo19/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Bayo19/subscriptions',
    organizations_url: 'https://api.github.com/users/Bayo19/orgs',
    repos_url: 'https://api.github.com/users/Bayo19/repos',
    events_url: 'https://api.github.com/users/Bayo19/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Bayo19/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'albertdugba',
    id: 26843996,
    node_id: 'MDQ6VXNlcjI2ODQzOTk2',
    avatar_url: 'https://avatars0.githubusercontent.com/u/26843996?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/albertdugba',
    html_url: 'https://github.com/albertdugba',
    followers_url: 'https://api.github.com/users/albertdugba/followers',
    following_url:
      'https://api.github.com/users/albertdugba/following{/other_user}',
    gists_url: 'https://api.github.com/users/albertdugba/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/albertdugba/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/albertdugba/subscriptions',
    organizations_url: 'https://api.github.com/users/albertdugba/orgs',
    repos_url: 'https://api.github.com/users/albertdugba/repos',
    events_url: 'https://api.github.com/users/albertdugba/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/albertdugba/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'meprap',
    id: 6134156,
    node_id: 'MDQ6VXNlcjYxMzQxNTY=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/6134156?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/meprap',
    html_url: 'https://github.com/meprap',
    followers_url: 'https://api.github.com/users/meprap/followers',
    following_url: 'https://api.github.com/users/meprap/following{/other_user}',
    gists_url: 'https://api.github.com/users/meprap/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/meprap/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/meprap/subscriptions',
    organizations_url: 'https://api.github.com/users/meprap/orgs',
    repos_url: 'https://api.github.com/users/meprap/repos',
    events_url: 'https://api.github.com/users/meprap/events{/privacy}',
    received_events_url: 'https://api.github.com/users/meprap/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'leonardo-costa',
    id: 53957923,
    node_id: 'MDQ6VXNlcjUzOTU3OTIz',
    avatar_url: 'https://avatars1.githubusercontent.com/u/53957923?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/leonardo-costa',
    html_url: 'https://github.com/leonardo-costa',
    followers_url: 'https://api.github.com/users/leonardo-costa/followers',
    following_url:
      'https://api.github.com/users/leonardo-costa/following{/other_user}',
    gists_url: 'https://api.github.com/users/leonardo-costa/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/leonardo-costa/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/leonardo-costa/subscriptions',
    organizations_url: 'https://api.github.com/users/leonardo-costa/orgs',
    repos_url: 'https://api.github.com/users/leonardo-costa/repos',
    events_url: 'https://api.github.com/users/leonardo-costa/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/leonardo-costa/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'devjaime',
    id: 26843824,
    node_id: 'MDQ6VXNlcjI2ODQzODI0',
    avatar_url: 'https://avatars3.githubusercontent.com/u/26843824?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/devjaime',
    html_url: 'https://github.com/devjaime',
    followers_url: 'https://api.github.com/users/devjaime/followers',
    following_url:
      'https://api.github.com/users/devjaime/following{/other_user}',
    gists_url: 'https://api.github.com/users/devjaime/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/devjaime/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/devjaime/subscriptions',
    organizations_url: 'https://api.github.com/users/devjaime/orgs',
    repos_url: 'https://api.github.com/users/devjaime/repos',
    events_url: 'https://api.github.com/users/devjaime/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/devjaime/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'paulinastefanska',
    id: 48317094,
    node_id: 'MDQ6VXNlcjQ4MzE3MDk0',
    avatar_url: 'https://avatars3.githubusercontent.com/u/48317094?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/paulinastefanska',
    html_url: 'https://github.com/paulinastefanska',
    followers_url: 'https://api.github.com/users/paulinastefanska/followers',
    following_url:
      'https://api.github.com/users/paulinastefanska/following{/other_user}',
    gists_url: 'https://api.github.com/users/paulinastefanska/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/paulinastefanska/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/paulinastefanska/subscriptions',
    organizations_url: 'https://api.github.com/users/paulinastefanska/orgs',
    repos_url: 'https://api.github.com/users/paulinastefanska/repos',
    events_url:
      'https://api.github.com/users/paulinastefanska/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/paulinastefanska/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'robcorreia',
    id: 29904660,
    node_id: 'MDQ6VXNlcjI5OTA0NjYw',
    avatar_url: 'https://avatars1.githubusercontent.com/u/29904660?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/robcorreia',
    html_url: 'https://github.com/robcorreia',
    followers_url: 'https://api.github.com/users/robcorreia/followers',
    following_url:
      'https://api.github.com/users/robcorreia/following{/other_user}',
    gists_url: 'https://api.github.com/users/robcorreia/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/robcorreia/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/robcorreia/subscriptions',
    organizations_url: 'https://api.github.com/users/robcorreia/orgs',
    repos_url: 'https://api.github.com/users/robcorreia/repos',
    events_url: 'https://api.github.com/users/robcorreia/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/robcorreia/received_events',
    type: 'User',
    site_admin: false,
  },
]
